name: ThisIsJustATest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: scgbear/azure-build-task@releases/v1
      with: 
        credentialssecret: azureserviceprincipal
        authtype: azure
