# lets force a build 
name: ThisIsJustATest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: scgbear/serverless-github-action@releases/v0.1.0
      with: 
        credentials: ${{ secrets.azureserviceprincipal }}
